### ISSUE TITLE
Some of us are older than 54!

### ISSUE THREAD

**Issue by frizziedad** [ronnnnnnnnnnnnn/etekcity_fitness_scale_ble#2] opened 2024-11-12 11:32 UTC
Configuration only allowed me to go back as far as 1970 when entering age! I was born in 1954.

**Comment by ronnnnnnnnnnnnn** [comment] 2024-11-13 17:56
Thanks for reporting the issue @frizziedad!
I'll look into it.

**Comment by ronnnnnnnnnnnnn** [comment] 2024-11-15 19:18
Ok, so the issue seems to have been with the DateSelector, whose date picker indeed only goes back to 1970. I've changed the code to use TextSelector of type DATE which doesn't seem to have the same issue, so it should now be resolved and allow setting earlier dates of birth.

The issue is now fixed in v0.2.4.


@frizziedad you can update to the latest version and the issue should be resolved.

**Closed by ronnnnnnnnnnnnn** 2024-11-15 19:18 UTC

**Comment by frizziedad** [comment] 2024-11-15 19:35
Hi Ron, thanks for fixing. I'll give it a try and let you know how I get on.

Cheers, John
